### ISSUE TITLE
Audiobook is not downloading.

### ISSUE THREAD

**Issue by pamaity93** [bunnykek/kuku-dl#15]
128kb.m3u8: No such file or directory
Traceback (most recent call last):
  File "C:\Python\Python313\Lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Documents\\Python Programming Files\\kuku-dl\\Downloads\\Hindi\\Audio book\\Read People Like A Book (2023) [Hindi]\\02. Chapter 1. Behavior Se Karein Guess Part - 1.m4a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\Python Programming Files\kuku-dl\kuku.py", line 183, in <module>
    KuKu(args.url).downAlbum()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\Documents\Python Programming Files\kuku-dl\kuku.py", line 171, in downAlbum
    self.downloadAndTag(epMeta, trackPath, srtPath,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        os.path.join(albumPath, 'cover.png'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Documents\Python Programming Files\kuku-dl\kuku.py", line 85, in downloadAndTag
    tag = MP4(path)
  File "C:\Python\Python313\Lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Python\Python313\Lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
         ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   writable, create) as h:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Python\Python313\Lib\contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "C:\Python\Python313\Lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Documents\\Python Programming Files\\kuku-dl\\Downloads\\Hindi\\Audio book\\Read People Like A Book (2023) [Hindi]\\02. Chapter 1. Behavior Se Karein Guess Part - 1.m4a'

**Comment by bunnykek** [comment]
Yes, they have patched their API. Now it will require premium account to download.

**Comment by Ajaypalmahecha** [comment]
I have premium account, it show this same error.

**Comment by bunnykek** [comment]
So i need to do some changes to support premium account.

**Comment by myselfayush010** [comment]
i did it changes. soon you will all have access

**Comment by sathishdevi1982** [comment]
> i did it changes. soon you will all have access

super bro.  It is working now

**Comment by bunnykek** [comment]
It is now fixed, do git pull and check updated readme
