### ISSUE TITLE
breaking on - link

### ISSUE THREAD

**Issue by Ex-Communicad0** [bunnykek/kuku-dl#7]
the-80_20-principle example url getting broken/error

Downloading 80/20 Principle
[out#0/ipod @ 0000027c569406c0] Error opening output H:\kuku-dl-main\kuku-dl-main\Downloads\Hindi\बाइट्स\The 8020 Principle (2024) [Hindi]\01. 80/20 Principle.m4a: No such file or directory
Error opening output file H:\kuku-dl-main\kuku-dl-main\Downloads\Hindi\बाइट्स\The 8020 Principle (2024) [Hindi]\01. 80/20 Principle.m4a.
Error opening output files: No such file or directory
Traceback (most recent call last):
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\kuku-dl-main\\kuku-dl-main\\Downloads\\Hindi\\बाइट्स\\The 8020 Principle (2024) [Hindi]\\01. 80/20 Principle.m4a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\kuku-dl-main\kuku-dl-main\kuku.py", line 163, in <module>
    KuKu(args.url).downAlbum()
  File "H:\kuku-dl-main\kuku-dl-main\kuku.py", line 151, in downAlbum
    self.downloadAndTag(epMeta, trackPath,
  File "H:\kuku-dl-main\kuku-dl-main\kuku.py", line 74, in downloadAndTag
    tag = MP4(path)
          ^^^^^^^^^
  File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\j\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'H:\\kuku-dl-main\\kuku-dl-main\\Downloads\\Hindi\\बाइट्स\\The 8020 Principle (2024) [Hindi]\\01. 80/20 Principle.m4a'

**Comment by bunnykek** [comment]
File sanitization error. Wait for some time. I am implementing lyrics, will fix this issue also.

**Comment by bunnykek** [comment]
Fixed it. Do git pull

**Comment by bolavefasfas** [comment]
solve-your-modern-problem-with-vedas
Album info:
Name: Solve Your Modern Problem With Vedas
Author: Samrat Singh
Language: Hindi
Date: 2023-02-27T10:01:19.117069+00:00
Age rating: 16+
Episodes: 12

Traceback (most recent call last):
  File "kuku.py", line , in <module>
    KuKu(args.url).downAlbum()
  File "kuku.py", line , in downAlbum
    'srt': ep['content']['subtitle_url'].strip(),
KeyError: 'subtitle_url'

**Comment by bunnykek** [comment]
> solve-your-modern-problem-with-vedas
> Album info:
> Name: Solve Your Modern Problem With Vedas
> Author: Samrat Singh
> Language: Hindi
> Date: 2023-02-27T10:01:19.117069+00:00
> Age rating: 16+
> Episodes: 12
> 
> Traceback (most recent call last):
>   File "kuku.py", line , in <module>
>     KuKu(args.url).downAlbum()
>   File "kuku.py", line , in downAlbum
>     'srt': ep['content']['subtitle_url'].strip(),
> KeyError: 'subtitle_url'

Do git pull

**Comment by bolavefasfas** [comment]
> > solve-your-modern-problem-with-vedas
> > Album info:
> > Name: Solve Your Modern Problem With Vedas
> > Author: Samrat Singh
> > Language: Hindi
> > Date: 2023-02-27T10:01:19.117069+00:00
> > Age rating: 16+
> > Episodes: 12
> > Traceback (most recent call last):
> > File "kuku.py", line , in 
> > KuKu(args.url).downAlbum()
> > File "kuku.py", line , in downAlbum
> > 'srt': ep['content']['subtitle_url'].strip(),
> > KeyError: 'subtitle_url'
> 
> Do git pull

Yes got fixed saw your other issue it was fixed there close this issue as its fixed.
Thanks for amazing project

**Comment by bunnykek** [comment]
Closing the issue. Reopen if required.
